/***** TRIGGERS ********************************************************/
trigger OnSpeaking(string text)
{
	obj_id target = getLookAtTarget(self);
	if (target == null)
		target = self;
		
	if (text == "age")
	{
		int age = getCurrentBirthDate() - getPlayerBirthDate(target);
		//debugSpeakMsg(self, "Age ->" + age);
		sendSystemMessageTestingOnly(self, "Age ->" + age);
	}
	

	return SCRIPT_CONTINUE;
}

