/***** INCLUDES ********************************************************/
include library.sui;
include library.utils;
include library.debug;
include library.xp;
include library.groundquests;

/***** CONSTANTS *******************************************************/
const string STF						= "dungeon/avatar_platform";
const string_id SEND_SIGNAL				= new string_id(STF, "lockbox_code");


/***** TRIGGERS ********************************************************/
trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{
	int menu = mi.addRootMenu( menu_info_types.ITEM_USE, SEND_SIGNAL );

		menu_info_data mid = mi.getMenuItemByType(menu_info_types.ITEM_USE);
			if ( mid == null )
			{
				return SCRIPT_CONTINUE;
			}

			mid.setServerNotify(true);

	return SCRIPT_CONTINUE;
}

trigger OnObjectMenuSelect(obj_id player, int item)
{
	if(item == menu_info_types.ITEM_USE)
	{
		groundquests.sendSignal(player, "mustafar_uplink_comm");
	}

 	return SCRIPT_CONTINUE;
}


