/**
 * Title:        raider_male.script
 * Description:  script for creating tusken.raider_male
 */

/***** INCLUDES ********************************************************/

include library.npc;
include library.weapons;

/***** CONSTANTS *******************************************************/

const string BASE_PATH					= "npc.create";
const string SCRIPT_ME					= BASE_PATH + ".tusken.raider_male";

/***** TRIGGERS ********************************************************/
trigger OnAttach()
{	
	weapons.createWeapon("object/weapon/melee/baton/baton_gaderiffi.iff", self, 1.0f);
	detachScript(self,SCRIPT_ME);
	return SCRIPT_CONTINUE;
}
