/**

 *
 * Title:        camp_luxury.script
 * Description:  camp_luxury

 */

//------------------------------------------------
// Inherits
//------------------------------------------------

inherits item.camp.camp_base;

//------------------------------------------------
// Methods
//------------------------------------------------

//------------------------------------------------
// OnAttach
//------------------------------------------------

trigger OnAttach()
{
	// Set our skill req.
	setObjVar( self, "campPower", 6 );
	setObjVar( self, "skillReq", 80 );

	return SCRIPT_CONTINUE;
}
