/**

 *
 * Title:        camp_quality.script
 * Description:  camp_quality

 */

//------------------------------------------------
// Inherits
//------------------------------------------------

inherits item.camp.camp_base;

//------------------------------------------------
// Methods
//------------------------------------------------

//------------------------------------------------
// OnAttach
//------------------------------------------------

trigger OnAttach()
{
	// Set our skill req.
	setObjVar( self, "campPower", 2 );
	setObjVar( self, "skillReq", 20 );

	return SCRIPT_CONTINUE;
}
