/**

 *
 * Title:        camp_elite.script
 * Description:  camp_elite

 */

//------------------------------------------------
// Inherits
//------------------------------------------------

inherits item.camp.camp_base;

//------------------------------------------------
// Methods
//------------------------------------------------

//------------------------------------------------
// OnAttach
//------------------------------------------------

trigger OnAttach()
{
	// Set our skill req.
	setObjVar( self, "campPower", 5 );
	setObjVar( self, "skillReq", 75 );

	return SCRIPT_CONTINUE;
}
