/**********************************************************************

 * Title:        temporary_structure.script
 * Description:  script that handles the temporary player structure

 **********************************************************************/

/***** TRIGGERS ********************************************************/
trigger OnObjectMenuRequest(obj_id player, menu_info mi)
{

	return SCRIPT_CONTINUE;
}
