/**

 *
 * Title:        invulnerable_wall.script
 * Description:  script for undamagable wall: POI = factoryliberation

 */

// Also used by the "prisonbreak" POI

//------------------------------------------------
// Includes
//------------------------------------------------

//------------------------------------------------
// Constants
//------------------------------------------------

const string LOG_NAME						= "poiFactoryLiberation Invulnerable Wall";

//------------------------------------------------
// Methods
//------------------------------------------------

//------------------------------------------------
// OnCombatDamaged
//------------------------------------------------

// This wall ignores combat damage.
trigger OnObjectDamaged( obj_id attacker, obj_id weapon, int damage )
{
	// Restore us to full health.
	int max_hitpoints = getMaxHitpoints(self);
	setHitpoints( self, max_hitpoints );

	return SCRIPT_CONTINUE;
}
