//------------------------------------------------
// Includes
//------------------------------------------------

include library.chat;

//------------------------------------------------
// Constants
//------------------------------------------------

//------------------------------------------------
// OnAttach
//------------------------------------------------

trigger OnAttach()
{
	setAnimationMood( self, "npc_imperial" );
	setInvulnerable( self, true );
	setName( self, "Under Inquisitor Holfheim" );

	return SCRIPT_CONTINUE;
}

//------------------------------------------------
// OnInitialize
//------------------------------------------------

trigger OnInitialize()
{
	setAnimationMood( self, "npc_imperial" );
	setInvulnerable( self, true );
	setName( self, "Under Inquisitor Holfheim" );

	return SCRIPT_CONTINUE;
}
