

/**
 * Include Libraries
 */
// include anyLibrary;	/** a .scriptlib file */
include library.utils;
include library.craftinglib;
include library.consumable;

inherits systems.crafting.food.crafted_items.crafting_artisan_ingredient;

void fillStomach( obj_id prototype, int filling )
{
	int[] stomach = {0, filling, 0};
	setObjVar( prototype, consumable.VAR_CONSUMABLE_STOMACH_VALUES, stomach );	// Suppress linting - We know this array will always be at least three elements long
}
